### ISSUE TITLE
Error in focusedProperty()

### ISSUE THREAD

**Issue by luizsistemas** [JFXtras/jfxtras.github.com#4]
focusedProperty().addListener does not fire in BigDecimalField. Here's a link to a project that tests and shows the error. Leaving the focus BigDecimalField nothing happens. Have the TextField2 works correctly.
https://dl.dropboxusercontent.com/u/72002301/JavaFXApplication8.rar

**Comment by tbee** [comment]
This is the repo for the website, please post issues in the correct repo; this belongs in jfxtras/jfxtras
